//! C/C++ toolchain discovery for clangd.
//!
//! clangd already discovers `compile_commands.json` on its own (it searches the
//! source file's parent directories and `build/` subdirectories), and a
//! compilation database is authoritative: when one exists we must not influence
//! the compiler, include paths or flags it specifies.
//!
//! The only gap is a project *without* a compilation database on Windows:
//! clangd then falls back to its built-in default target (MSVC), so a MinGW
//! project would resolve `<vector>` to the MSVC STL. To fix that without
//! hardcoding any toolchain path, we use clangd's official configuration:
//!
//! - detect a gcc-compatible driver (`g++`, then `gcc`) on `PATH`;
//! - if found and the workspace has no compilation database and no `.clangd`
//!   of its own, write a small managed `.clangd` with
//!   `CompileFlags: Compiler: <driver>` (this is what selects the toolchain);
//! - always run clangd with `--enable-config` (so `.clangd` files are honored)
//!   and `--query-driver=<driver>` (so clangd may invoke it to extract the
//!   system include paths, i.e. libstdc++).
//!
//! The generated `.clangd` is marked and removed as soon as a compilation
//! database appears, so a project's own toolchain always wins. No STL include
//! paths are hardcoded and clangd itself is never modified.

use std::path::{Path, PathBuf};

/// First line of the `.clangd` file this module owns.
const MANAGED_MARKER: &str = "# Managed by lite-ide";

#[cfg(windows)]
const GXX_NAMES: &[&str] = &["g++.exe"];
#[cfg(not(windows))]
const GXX_NAMES: &[&str] = &["g++"];

#[cfg(windows)]
const GCC_NAMES: &[&str] = &["gcc.exe"];
#[cfg(not(windows))]
const GCC_NAMES: &[&str] = &["gcc"];

/// The clangd arguments to add for a workspace (see the module docs).
pub fn clangd_args(workspace: &Path) -> Vec<String> {
    let cxx = detect_compiler(GXX_NAMES);
    let cc = detect_compiler(GCC_NAMES);
    build_clangd_args(workspace, cxx.as_deref(), cc.as_deref())
}

/// Pure(std-ish) core: decides the args and manages the fallback `.clangd`.
/// Kept separate from `PATH` detection so it can be unit tested.
fn build_clangd_args(workspace: &Path, cxx: Option<&Path>, cc: Option<&Path>) -> Vec<String> {
    let mut args = vec!["--enable-config".to_string()];

    let mut drivers: Vec<String> = Vec::new();
    for driver in [cxx, cc].into_iter().flatten() {
        let driver = to_forward_slashes(driver);
        if !drivers.contains(&driver) {
            drivers.push(driver);
        }
    }
    if !drivers.is_empty() {
        // Whitelists gcc-compatible drivers clangd may execute to read the
        // system include paths. It does not override any compilation database.
        args.push(format!("--query-driver={}", drivers.join(",")));
    }

    if find_compile_commands(workspace).is_some() {
        // The project's compilation database decides the toolchain; make sure
        // our fallback can never shadow its compiler.
        remove_managed_clangd(workspace);
    } else if let Some(compiler) = cxx.or(cc) {
        ensure_managed_clangd(workspace, compiler);
    } else {
        // Nothing to fall back to; drop any stale managed file.
        remove_managed_clangd(workspace);
    }

    args
}

/// The compilation database in the workspace root or `build/`, if any.
fn find_compile_commands(workspace: &Path) -> Option<PathBuf> {
    for candidate in [
        workspace.join("compile_commands.json"),
        workspace.join("build").join("compile_commands.json"),
    ] {
        if candidate.is_file() {
            return Some(candidate);
        }
    }
    None
}

fn detect_compiler(names: &[&str]) -> Option<PathBuf> {
    let path = std::env::var_os("PATH")?;
    let dirs: Vec<PathBuf> = std::env::split_paths(&path).collect();
    find_in_paths(&dirs, names)
}

/// First existing `dir/name` following the order of `dirs`, then `names`.
fn find_in_paths(dirs: &[PathBuf], names: &[&str]) -> Option<PathBuf> {
    for dir in dirs {
        for name in names {
            let candidate = dir.join(name);
            if candidate.is_file() {
                return Some(candidate);
            }
        }
    }
    None
}

fn to_forward_slashes(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

fn managed_clangd_path(workspace: &Path) -> PathBuf {
    workspace.join(".clangd")
}

/// Whether the file at `path` was generated by this module.
fn is_managed_clangd(path: &Path) -> bool {
    match std::fs::read_to_string(path) {
        Ok(text) => text
            .lines()
            .next()
            .map(|line| line.trim_start().starts_with(MANAGED_MARKER))
            .unwrap_or(false),
        Err(_) => false,
    }
}

fn write_managed_clangd(path: &Path, compiler: &Path) {
    let compiler = to_forward_slashes(compiler);
    let content = format!(
        "{MANAGED_MARKER}. Fallback C/C++ compiler used because this workspace\n\
         # has no compile_commands.json. Safe to delete; it is regenerated when needed.\n\
         CompileFlags:\n\
         \x20 Compiler: {compiler}\n"
    );
    if let Err(err) = std::fs::write(path, content) {
        eprintln!("could not write the fallback .clangd: {err}");
    }
}

/// Create or refresh the managed `.clangd`, but never touch a user-owned file
/// (a real `.clangd` file or a legacy `.clangd` directory).
fn ensure_managed_clangd(workspace: &Path, compiler: &Path) {
    let path = managed_clangd_path(workspace);
    if path.exists() && (!path.is_file() || !is_managed_clangd(&path)) {
        return;
    }
    write_managed_clangd(&path, compiler);
}

fn remove_managed_clangd(workspace: &Path) {
    let path = managed_clangd_path(workspace);
    if path.is_file() && is_managed_clangd(&path) {
        if let Err(err) = std::fs::remove_file(&path) {
            eprintln!("could not remove the fallback .clangd: {err}");
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    static COUNTER: AtomicU64 = AtomicU64::new(0);

    fn tmp_dir() -> PathBuf {
        let n = COUNTER.fetch_add(1, Ordering::SeqCst);
        let dir = std::env::temp_dir().join(format!("lite_ide_cpp_{}_{}", std::process::id(), n));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }

    #[test]
    fn find_in_paths_respects_order() {
        let a = tmp_dir();
        let b = tmp_dir();
        std::fs::write(b.join("g++.exe"), "").unwrap();
        let dirs = vec![a.clone(), b.clone()];
        assert_eq!(
            find_in_paths(&dirs, &["g++.exe"]),
            Some(b.join("g++.exe"))
        );
        assert_eq!(find_in_paths(&dirs, &["missing"]), None);
        let _ = std::fs::remove_dir_all(&a);
        let _ = std::fs::remove_dir_all(&b);
    }

    #[test]
    fn find_compile_commands_checks_root_then_build() {
        let ws = tmp_dir();
        assert_eq!(find_compile_commands(&ws), None);
        std::fs::create_dir_all(ws.join("build")).unwrap();
        std::fs::write(ws.join("build").join("compile_commands.json"), "[]").unwrap();
        assert_eq!(
            find_compile_commands(&ws),
            Some(ws.join("build").join("compile_commands.json"))
        );
        std::fs::write(ws.join("compile_commands.json"), "[]").unwrap();
        assert_eq!(
            find_compile_commands(&ws),
            Some(ws.join("compile_commands.json"))
        );
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn writes_managed_fallback_when_no_database() {
        let ws = tmp_dir();
        let compiler = Path::new(r"D:\tools\mingw\bin\g++.exe");
        let args = build_clangd_args(&ws, Some(compiler), None);

        assert!(args.iter().any(|a| a == "--enable-config"));
        assert!(args
            .iter()
            .any(|a| a == "--query-driver=D:/tools/mingw/bin/g++.exe"));

        let clangd = std::fs::read_to_string(ws.join(".clangd")).unwrap();
        assert!(clangd.starts_with(MANAGED_MARKER));
        assert!(clangd.contains("Compiler: D:/tools/mingw/bin/g++.exe"));
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn removes_managed_fallback_when_database_exists() {
        let ws = tmp_dir();
        let compiler = Path::new(r"D:\tools\mingw\bin\g++.exe");
        build_clangd_args(&ws, Some(compiler), None);
        assert!(ws.join(".clangd").is_file());

        std::fs::write(ws.join("compile_commands.json"), "[]").unwrap();
        build_clangd_args(&ws, Some(compiler), None);
        assert!(!ws.join(".clangd").exists(), "fallback must not shadow a database");
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn never_overwrites_a_user_clangd() {
        let ws = tmp_dir();
        let user = "CompileFlags:\n  Compiler: cl\n";
        std::fs::write(ws.join(".clangd"), user).unwrap();
        build_clangd_args(&ws, Some(Path::new(r"D:\tools\g++.exe")), None);
        assert_eq!(std::fs::read_to_string(ws.join(".clangd")).unwrap(), user);
        let _ = std::fs::remove_dir_all(&ws);
    }

    #[test]
    fn build_dir_database_is_detected() {
        let ws = tmp_dir();
        std::fs::create_dir_all(ws.join("build")).unwrap();
        std::fs::write(ws.join("build").join("compile_commands.json"), "[]").unwrap();
        let compiler = Path::new(r"D:\tools\g++.exe");
        let args = build_clangd_args(&ws, Some(compiler), None);
        // No fallback file, because the build/ database is authoritative.
        assert!(!ws.join(".clangd").exists());
        assert!(args.iter().any(|a| a == "--enable-config"));
        let _ = std::fs::remove_dir_all(&ws);
    }
}
